name: Node.js CI

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js with yarn
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'yarn'
    - run: yarn install
    - run: yarn scrape
    - run: git stash
    - run: git chekout data
    - run: git stash pop
    - run: git status
