name: Scrape Data

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js with yarn
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Scrape Dataset
      run: yarn scrape
    - name: Prepare Scraped Results
      run: |
        mkdir /tmp/res
        cp -r data /tmp/res
    - uses: actions/checkout@v2
      with:
        ref: data
    - run: |
        echo "* $(date)" >> update.log
        cp -r /tmp/res/data .
        git config user.name updater-bot
        git config user.email github-actions@github.com
        git add .
        git commit -m "updater-bot ${date}"
        git push
